### ISSUE TITLE
Doesn't upload

### ISSUE THREAD

**Issue by civanescu** [taweili/ardublock#174]
The software doesn't upload! 
When upload it says: Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: processing.app.Editor.setText(Ljava/lang/String;)V
Last error being: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

My Arduino is 1.8.4. Thank you!

**Comment by danielfsc** [comment]
Try arduino 1.8.2.

Em 23 de set de 2017 9:25 AM, "Claudiu Ivanescu" <notifications@github.com>
escreveu:

**Comment by civanescu** [comment]
Thank you, actually I was using (accidentally) a older version of ardublocks. Now it's perfect.
